### ISSUE TITLE
[9.0] Odoo + Docker: Printer ZPL II - Installation error (security file)

### ISSUE THREAD

**Issue by cristianpilon** [OCA/report-print-send#166]
Hi OCA team. We've installed Odoo in a Docker container (using Ubuntu 18.04) and we are getting the following error when we try to install the module **printer_zpl2**:

```
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 324, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 317, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 967, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 900, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/extra-addons/ingadhoc-odoo-support/adhoc_modules/wizard/module_upgrade.py", line 53, in upgrade_module
    super(BaseModulePreUpgrade, self).upgrade_module()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/wizard/base_module_upgrade.py", line 87, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 370, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 263, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 173, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 99, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 843, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 907, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo printer_zpl2: no se pudo procesar el archivo printer_zpl2/security/ir.model.access.csv:
Line 1 : No se han encontrado registros coincidentes para id. externo 'base_report_to_printer.printing_group_user' en el campo 'Group'
```

The error is in spanish but the translation to english would be: _No matching record found for external id 'base_report_to_printer.printing_group_user' in field 'Group'_

These are the version of the modules:
Report to printer: 9.0.2.1.1
Printer ZPL II: 9.0.1.0.0

Please let us know if you need more information.

Thanks.

**Comment by pedrobaeza** [comment]
Do you have `base_report_to_printer` in your addons path?

**Comment by cristianpilon** [comment]
Yes. I've added base_report_to_printer to the addons folder and installed it.

**Comment by pedrobaeza** [comment]
Then there's something weird with your deployment. The XML-ID is there:

https://github.com/OCA/report-print-send/blob/9.0/base_report_to_printer/security/security.xml#L8

Any way, it's not a problem of the module itself, as you can see it's working in http://3348130-9-0-e93513.runbot3.odoo-community.org/, so closing this.
