### ISSUE TITLE
Module not working on odoo.sh

### ISSUE THREAD

**Issue by younismahsud** [OCA/report-print-send#176]
I setup everything on odoo.sh. It fetched the printers from the cups server. I configured the invoice report to send to printer. But when I click to print invoice report then I got the following error message.

> Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/base_report_to_printer/models/ir_actions_report.py", line 117, in print_document
    **behaviour)
  File "/home/odoo/src/user/base_report_to_printer/models/printing_printer.py", line 134, in print_document
    file_name, report=report, **print_opts)
  File "/home/odoo/src/user/base_report_to_printer/models/printing_printer.py", line 180, in print_file
    options=options)
cups.IPPError: (1280, 'No such file or directory')

Is this something that you can help me please?

I installed the modules on my local machine but it is throwing the same error. It is only working if odoo and printer are in the same network.
Thanks

**Comment by AhmadNader83** [comment]
Hi,.. how you install pycups  in odoo sh ?

**Comment by JPML94** [comment]
It is not possible. https://www.odoo.com/documentation/user/13.0/odoo_sh/advanced/frequent_technical_questions.html#can-you-install-pycups-or-some-similar-library-linked-to-cups

**Comment by younismahsud** [comment]
Thank you for your feedback.

**Comment by omalbastin** [comment]
still not working in odoo.sh?
