### ISSUE TITLE
printer_zpl2: crash when module is NOT installed

### ISSUE THREAD

**Issue by alexis-via** [OCA/report-print-send#179]
On Odoo v10, when the module printer_zpl2 is in your addons_path and the zpl2 lib is not installed, you get this:

```
2019-08-20 07:57:13,863 27445 INFO ? werkzeug: 127.0.0.1 - - [20/Aug/2019 07:57:13] "GET /web/static/src/img/placeholder.png HTTP/1.1" 500 -
2019-08-20 07:57:13,879 27445 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/erp/odoo/odoo/service/server.py", line 307, in app
    return self.app(e, s)
  File "/home/odoo/erp/odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/erp/odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/erp/odoo/odoo/http.py", line 1325, in __call__
    self.load_addons()
  File "/home/odoo/erp/odoo/odoo/http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/home/odoo/erp/odoo/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/home/odoo/erp/report-print-send/printer_zpl2/__init__.py", line 5, in <module>
    from . import models
channel 4: open failed: connect failed: Connection refusedls/__init__.py", line 5, in <module>
    from . import printing_label_zpl2_component
  File "/home/odoo/erp/report-print-send/printer_zpl2/models/printing_label_zpl2_component.py", line 16, in <module>
    class PrintingLabelZpl2Component(models.Model):
  File "/home/odoo/erp/report-print-send/printer_zpl2/models/printing_label_zpl2_component.py", line 37, in PrintingLabelZpl2Component
    (zpl2.BARCODE_CODE_11, 'Code 11'),
NameError: name 'zpl2' is not defined
```

**Comment by etobella** [comment]
There is a missibg library dependency. A try import ahould be needed, but you should make pip install -r requirements.txt in order to solve it easily

**Comment by alexis-via** [comment]
There is already a try/import in the code, but it's not enough in this particular case, because the lib is used in a field definition.
