### ISSUE TITLE
Error when printing

### ISSUE THREAD

**Issue by terencefaul** [OCA/report-print-send#206]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_report_to_printer/models/ir_actions_report.py", line 111, in print_document
    self, document, doc_format=self.report_type, **behaviour
  File "/usr/lib/python3/dist-packages/odoo/addons/base_report_to_printer/models/printing_printer.py", line 134, in print_document
    return self.print_file(file_name, report=report, **print_opts)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_report_to_printer/models/printing_printer.py", line 174, in print_file
    connection.printFile(self.system_name, file_name, file_name, options=options)
cups.IPPError: (1280, 'No such file or directory')

**Comment by FranciscoBigWings** [comment]
How to solve this error?

I have the same error in Ubuntu 18 LTS and Odoo V12

**Comment by FranciscoBigWings** [comment]
My error cups.IPPError: (1280, 'No such file or directory') was related to bad configuration of cupsd.conf and in general of CUPS

**Comment by maicoldlb** [comment]
> My error cups.IPPError: (1280, 'No such file or directory') was related to bad configuration of cupsd.conf and in general of CUPS

Como solucionaste el problema ?

**Comment by FranciscoBigWings** [comment]
The error is not from Odoo module. The error is was CUPS server. Properly install and configure your CUPS server and printer, the next step be first trying to print directly in the printer and document through CUPS, once you have done that, I am sure that you wont have any error in Odoo.

**Comment by flotho** [comment]
Hi @FranciscoBigWings any chance to give more precision.
I have the same issue but when I try to print by shel CLI an Odoo file to the printer it works but with the same report from Odoo I have the same message as yours.
More advice on what you changed in the cups conf would be appreciated.
regards
