### ISSUE TITLE
8.0 base_report_to_printer failure through non existent ir.model.access.csv

### ISSUE THREAD

**Issue by msteinfeld-intero** [OCA/report-print-send#24]
Hello,

we have a system for the customer, where several functions end with a failure because of non existent security groups.

```
2015-01-27 17:18:54,867 17672 WARNING hhw_testing_m2 openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: printing.printer.polling
2015-01-27 17:18:54,868 17672 ERROR hhw_testing_m2 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/calendar/controllers/main.py", line 61, in notify
    res = registry.get("calendar.alarm_manager").get_next_notif(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/calendar/calendar.py", line 472, in get_next_notif
    partner = self.pool.get('res.users').browse(cr, uid, uid, context=context).partner_id
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 780, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5834, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 53, in get
    raise self.exception
AccessError: ('AccessError', 'No value found for res.users(4,).partner_id')
```

I don't know wether the second failure is about that,but i am testing that at the moment.

**Comment by guewen** [comment]
Hello,

do you use the HEAD of the 8.0 branch?
The model `printing.printer.polling` does no longer exist in `base_report_to_printer`.

**Comment by msteinfeld-intero** [comment]
Ah ok :+1:  we wasn't up to date.
Thank you!
