### ISSUE TITLE
[14.0] TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by sya-odoo** [OCA/report-print-send#274]
## Module
base_report_to_printer

## Describe the bug
When a report is configured to be "Send to Printer" and has the field `print_report_name` (Printed Report Name) set, an error will be thrown when printing.
It seems to be caused by a wrong import of `safe_eval` in `base_report_to_printer/models/ir_actions_report.py`.

## To Reproduce
**Affected versions**: 14.0

1. Configure a report with the field "Printed Report Name" set to be "Send to Printer"
2. Print it
3. Error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1392, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/OCA/report-print-send/base_report_to_printer/models/ir_actions_report.py", line 112, in print_document
    report_file_names = [
  File "/home/odoo/src/user/OCA/report-print-send/base_report_to_printer/models/ir_actions_report.py", line 113, in <listcomp>
    safe_eval(self.print_report_name, {"object": obj, "time": time})
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'module' object is not callable
```

**Additional context**
The behavior comes from this commit: https://github.com/OCA/report-print-send/commit/d572938c7074222ff5749dec96839443963dbcc4

**Comment by gdgellatly** [comment]
There is a pr to resolve this already #269
