### ISSUE TITLE
error when printing with fresh install

### ISSUE THREAD

**Issue by HansG130** [OCA/report-print-send#314]
module: base_report_to_printer
version: 16.0

**Steps to reproduce**
Install new database, install inventory, install base_report_to_printer

**Current behavior**
as soon as we installed the module we get an error message when we want to print. even if we set it to send to client. It always gives a message  
 _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

File "/opt/odoo/addons/base_report_to_printer/models/ir_actions_report.py", line 81, in behaviour
    self.ensure_one()

Traceback (most recent call last):
  File "/opt/odoo/odoo16/odoo/models.py", line 5112, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo16/addons/web/controllers/report.py", line 123, in report_download
    response = self.report_routes(reportname, converter=converter, context=context, **data)
  File "/opt/odoo/odoo16/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo16/addons/web/controllers/report.py", line 45, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/opt/odoo/addons/base_report_to_printer/models/ir_actions_report.py", line 163, in _render_qweb_pdf
    behaviour = self.behaviour()
  File "/opt/odoo/addons/base_report_to_printer/models/ir_actions_report.py", line 81, in behaviour
    self.ensure_one()
  File "/opt/odoo/odoo16/odoo/models.py", line 5115, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: ir.actions.report()

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://192.168.253.231:8069/web/assets/debug/web.assets_backend.js:10149:19) (/web/static/src/core/network/rpc_service.js:34)
    at decoder.onload (http://192.168.253.231:8069/web/assets/debug/web.assets_backend.js:10037:29) (/web/static/src/core/network/download.js:520)

**Expected behavior**

**Comment by andreampiovesana** [comment]
also for me, I disinstalled base_report_to_printer and after no more errors

**Comment by snowtianyou** [comment]
Odoo16 I also appear here
def behaviour(self):  method ERROR
self for none value
execute self.ensure_one() error
