### ISSUE TITLE
Error whil Updating printers from CUPS

### ISSUE THREAD

**Issue by plennix** [OCA/report-print-send#344]
After setting up the module and installed CUPS on the server, i am getting an error as below while trying to click on Update printers from Cups:
Please note that the printer is installed in Cups and i can print test pages from there, also cups is accessible by server-ip-address:631 

Traceback (most recent call last):
  File "/odoo-stg/odoo-stg-server/odoo/http.py", line 1586, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo-stg/odoo-stg-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoo-stg/odoo-stg-server/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo-stg/odoo-stg-server/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo-stg/odoo-stg-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo-stg/odoo-stg-server/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo-stg/odoo-stg-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo-stg/odoo-stg-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo-stg/odoo-stg-server/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo-stg/odoo-stg-server/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo-stg/odoo-stg-server/cbc/base_report_to_printer/wizards/printing_printer_update_wizard.py", line 19, in action_ok
    self.env["printing.server"].search([]).update_printers(raise_on_error=True)
  File "/odoo-stg/odoo-stg-server/cbc/base_report_to_printer/models/printing_server.py", line 107, in update_printers
    printers = connection.getPrinters()
cups.IPPError: (1280, 'Success')

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://10.30.1.30/web/assets/435-3cdb3e1/web.assets_backend.min.js:972:274
    makeErrorFromResponse@http://10.30.1.30/web/assets/435-3cdb3e1/web.assets_backend.min.js:976:163
    jsonrpc/promise</<@http://10.30.1.30/web/assets/435-3cdb3e1/web.assets_backend.min.js:984:34

**Comment by ivs-cetmix** [comment]
Hi @plennix thank you for your report. Could you please update your ticket to make it usable?
