### ISSUE TITLE
Update Printers from CUPS throws error in ODOO 9.

### ISSUE THREAD

**Issue by metrogeekythinker** [OCA/report-print-send#61]
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 353, in old_api
    recs = self.browse(cr, uid, [], context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5380, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 752, in __new__
    self.cr, self.uid, self.context = self.args = (cr, uid, frozendict(context))
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

**Comment by livingmine** [comment]
I experienced the same issue. Any update on this?

**Comment by yvaucher** [comment]
@lasley you have an idea on this? It reminds me nothing from former version of the module.

The issue might be fixed by this: https://github.com/OCA/report-print-send/pull/62/files
However I don't have the setup to test it right now.

**Comment by efarias** [comment]
I'm also experiencing this issue, i need some help please!

**Comment by lasley** [comment]
@yvaucher  - yup I think you're on point with the thought that this is wire crossing in the APIs. I am able to replicate this in my local, so should be able to make a fix PR in the next few days.

**Comment by lasley** [comment]
Closing to track in PR #62
