### ISSUE TITLE
base_report_to_printer fails  (branch 9)

### ISSUE THREAD

**Issue by AlainVanUtterbeeck** [OCA/report-print-send#87]
Hello,

I installed the latest version (in branch 9) of base_report_to_printer as I saw it had been modified recently. When trying to print a report to a printer, I get following error:

Traceback (most recent call last):
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alain/DRGTDEV/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/home/alain/DRGTDEV/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/home/alain/DRGTDEV/odoo/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/alain/DRGTDEV/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alain/DRGTDEV/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alain/DRGTDEV/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/alain/DRGTDEV/odoo/custom/base_report_to_printer/models/report.py", line 15, in print_document
    record_ids, report_name, html=html, data=data)
  File "/home/alain/DRGTDEV/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

**Comment by AlainVanUtterbeeck** [comment]
addition: I have just figured out that if I uninstall the MIS Builder (in account_financial_reporting), printing to printer works, so I suppose this issue should be closed and a new one added to the account_financial_reporting ?

**Comment by AlainVanUtterbeeck** [comment]
solved in mis_builder
