### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by jayo2005** [OCA/report-print-send#93]
Hi I am getting an error from the base_report_to_printer module.

```
2017-07-04 09:42:49,857 32538 ERROR dsc2 openerp.addons.base.ir.ir_cron: Call of self.pool.get('printing.server').action_update_jobs(cr, uid, *()) failed in Job 6
Traceback (most recent call last):
  File "/home/jason/odoo/odoo/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/home/jason/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/jason/odoo/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/jason/odoo/odoo/customaddons/base_report_to_printer/models/printing_server.py", line 109, in action_update_jobs
    return self.update_jobs()
  File "/home/jason/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/jason/odoo/odoo/customaddons/base_report_to_printer/models/printing_server.py", line 215, in update_jobs
    job_obj.create(job_values)
  File "/home/jason/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/jason/odoo/odoo/openerp/models.py", line 4174, in create
    record = self.browse(self._create(old_vals))
  File "/home/jason/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/jason/odoo/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/jason/odoo/odoo/openerp/models.py", line 4318, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/home/jason/odoo/odoo/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/jason/odoo/odoo/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "printer_id" violates not-null constraint
DETAIL:  Failing row contains (32381, 0, 1, processing-to-stop-point, 2017-06-30 14:34:33, 2017-07-04 09:42:49.799507, , completed, null, 8, 1, 2017-07-04 09:42:49.799507, t, 2017-06-30 14:34:43, 2017-06-30 14:34:33, null).
```

**Comment by pedrobaeza** [comment]
This is because you have an incorrect server without printer.

**Comment by willmakenoise** [comment]
I'm also getting this error.

@pedrobaeza My Odoo is running on a remote server, so I've added a server to the print module that connects to my local machine (with cups opened to allow remote connections).
Odoo finds my local printers and everything works.. besides getting this error.

This is the only print server that is configured in Odoo.. so I'm not sure what you mean saying "inncorrect server without printer".  

EDIT:
Seems like all printers on the cups server has to be shared to avoid this error.
The code should probably take this into account when running update_jobs().

BTW: Great work on this module. It's really useful!

**Comment by pedrobaeza** [comment]
@sylvain-garancher what do you think about the share thing that @willmakenoise comments?

**Comment by Garamotte** [comment]
If the printer is not shared, it will not be listed when listing printers, but if the pycups module retrieves jobs of hidden printers, then yes, it will crash. I think that @willmakenoise explanation is right.

However, I don't have time to fix it.

**Comment by pedrobaeza** [comment]
Reopening this then with the latest explanation for seeing if someone can fix that thing. @willmakenoise maybe you can propose a PR?
