### ISSUE TITLE
[Odoo 9] Error when installing "External ID not found in the system: base_report_to_printer.view_printing_users_prefs" while parsing /media/storage/Odoo/third-party-addons/google_cloud_print/views/res_users_view.xml:30"

### ISSUE THREAD

**Issue by fnaquira** [OCA/report-print-send#99]
I get this error when I try to install the module, I thought it was my version of odoo but then I installed a new one with everything by default (only the main modules provided by odoo) and it still fails

`Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 697, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 780, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 791, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1001, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/opt/odoo/odoo/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base_report_to_printer.view_printing_users_prefs" while parsing /media/storage/Odoo/third-party-addons/google_cloud_print/views/res_users_view.xml:30, near`
<record model="ir.ui.view" id="view_users_form_simple_modif">
        <field name="name">res.users.form.printing</field>
        <field name="model">res.users</field>
        
        
        <field name="inherit_id" ref="base_report_to_printer.view_printing_users_prefs"/>
        <field name="arch" type="xml">
            <group name="printing" position="before">
                <group string="Google Cloud Print" name="gcp">
                    <field name="google_cloudprint_rtoken" invisible="1"/>
                    <label for="google_cloudprint_authorization_code"/>
                    <div class="oe_inline">
                        <field name="google_cloudprint_authorization_code" class="oe_inline"/>
                        <field name="google_cloudprint_uri" widget="url" text="&#8658; Generate Google Authorization Code" class="oe_inline oe_bold"/>
                        <button name="update_user_gc_printers" type="object" string="&#8658; Refresh Printers" class="oe_link" attrs="{'invisible': [('google_cloudprint_authorization_code', '=', False)]}"/>
                    </div>
                    <label for="gcprinter_ids" attrs="{'invisible': [('google_cloudprint_rtoken', '=', False)]}"/>
                    <div class="oe_inline" attrs="{'invisible': [('google_cloudprint_rtoken', '=', False)]}">
                        
                        <field name="gcprinter_ids" class="oe_inline" widget="many2many_tags" readonly="0"/>
                        
                        <a href="https://www.google.com/cloudprint#jobs" target="_blank">&#8658; Check Jobs on GCP</a>
                        <a href="https://www.google.com/cloudprint#printers" target="_blank">&#8658; Manage Printers on GCP</a>
                    </div>
                </group>
            </group>
        </field>
    </record>

**Comment by Garamotte** [comment]
Hello,

This xml_id has been removed during the v9 migration of the `base_report_to_printer` module: https://github.com/OCA/report-print-send/commit/4b080d7a631675d1988c7442f119dda2d52ee9b3#diff-5b5b2a017e1cc2a4a8b85e3c103281e0L20

It seems that the `google_cloud_print` module is made to work with another version of this module: https://github.com/ingadhoc/reporting-engine/blob/9.0/google_cloud_print/views/res_users_view.xml#L33-L35

I think uncommenting the commented lines and commenting the one that is crashing will fix your issue.
You can also submit your issue to the developer of that module: https://github.com/ingadhoc/reporting-engine/issues/new

**Comment by fnaquira** [comment]
Thank you! I could install it but now I'm getting an error when I try to get all my Google Cloud Printers:

`The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: server_id - server.id] `

I know it is kind of working correctly because I can see my printers listed on the console, and the console is sending and error of bad query:

`2017-07-21 15:52:22,309 9460 INFO test openerp.sql_db: bad query: INSERT INTO "printing_printer" ("id", "system_name", "status", "name", "default", "uri", "location", "gc_user_id", "printer_type", "model", "status_message", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('printing_printer_id_seq'), 'EPSON TM-T20II Receipt', 'unknown', 'EPSON TM-T20II Receipt', false, 'a17d427c-bde0-7682-0fe8-297dcfd7196b', '2998a4ff-bcb5-43d2-a928-aad0b9d3f2a0', NULL, 'gcp', 'GOOGLE', 'OFFLINE', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id`

**Comment by Garamotte** [comment]
Again, this is not an issue from the `base_report_to_printer` module, but from `google_cloud_print`, which is not maintained by the OCA.

Please submit your issue to the developer of that module: https://github.com/ingadhoc/reporting-engine/issues/new
